### ISSUE TITLE
Confused about code/ vs Software/ folders

### ISSUE THREAD

**Issue by sofian** [Xmodal/Totem#32]
There is a code and a Software folder on the root of the repo: what do they mean? Where should I put my code?

**Comment by alx-s** [comment]
There must have been an issue with a push at some point. The software folder shouldn't be there, everything should be in the code, as described in the readme.

**Comment by alx-s** [comment]
I'm fetching and restructuring the git now

**Comment by alx-s** [comment]
I'm still confused about the presence of the "code/Processing" folder. This one should not be there (I don't seem to be able to delete it...)

**Comment by sofian** [comment]
If you are on a Mac it is possible that because you have a Code and code folders there might be some kind of conflict (Mac OS is NOT case-sensitive so it might see both folders as being the same).

**Comment by sofian** [comment]
Try renaming one of the folders first, then moving everything into the other, then deleting the empty folder.

**Comment by alx-s** [comment]
good, done... mac...
